# Generated by Django 6.0.7 on 2026-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person_booking', models.CharField(max_length=50)),
                ('phone_of_person_booking', models.CharField(max_length=13)),
                ('email_of_person_booking', models.EmailField(max_length=100)),
                ('project', models.CharField(max_length=50)),
                ('number_of_days_to_book', models.IntegerField(default=1)),
                ('booking_date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('booking_made_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RtkPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model', models.CharField(max_length=100)),
                ('machine_brand', models.CharField(max_length=100)),
            ],
        ),
    ]
