# Generated by Django 6.0.7 on 2026-08-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='project',
            new_name='project_location',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='booking_date',
            new_name='rental_start_date',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='number_of_days_to_book',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='machine_booked',
            field=models.CharField(default='gintec rtk', max_length=100),
            preserve_default=False,
        ),
    ]
