# Generated by Django 6.0.7 on 2026-08-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0002_rename_project_bookingdetails_project_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='message',
            field=models.CharField(default='place holder', max_length=2000),
            preserve_default=False,
        ),
    ]
