# Generated by Django 6.0.7 on 2026-08-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0003_bookingdetails_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='rental_end_date',
            field=models.DateField(default='2026-1-1'),
            preserve_default=False,
        ),
    ]
