# Generated by Django 6.0.7 on 2026-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0004_bookingdetails_rental_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addres_of_visitor', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('visiting_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
