# Generated by Django 6.0.7 on 2026-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0005_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtkpresent',
            name='machine_brand',
        ),
        migrations.AddField(
            model_name='rtkpresent',
            name='machine_daily_rate',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtkpresent',
            name='machine_description',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
