# Generated by Django 6.0.7 on 2026-08-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrtk', '0006_remove_rtkpresent_machine_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
